Required updates for Cropper.
ASUWebPlatforms/webspark-theme-renovation pull request #170
Opened 2021-07-19 15:45 UTC by deptant

This update includes templates for media-library. There are css updates to reflect the modal changes in both the backend and the front end used by layout builder.

Early iterations of the theme used some form templates which was bad practise and caused many issues with media library and cropper. These have been renamed to -old. I have left them in place, in case we notice any issues caused by removing them. If this happens, they should be renamed/replaced with more specific templates using template suggestions.

Specific templates have been introduced for the cropper image in Layout Builder as the front end was causing issues.

2021-07-19 21:22 UTC, mlsamuelson requested changes
@duarte-daniela Looks like there is some Git metadata formatting that snuck into css/ckeditor-override.css. See the comments I've added in the content.

2021-07-19 21:22 UTC, mlsamuelson commented on css/ckeditor-override.css
> +=======
@duarte-daniela Looks like some Git conflict for some other sort of Git formatting here.

2021-07-19 21:22 UTC, mlsamuelson commented on css/ckeditor-override.css
> +>>>>>>> Stashed changes
@duarte-daniela Another bit that needs cleanup.

2021-07-20 12:19 UTC, ovista-dept approved these changes
I removed the unwanted get formatting charters. This looks good to me.

2021-07-21 04:08 UTC, mlsamuelson approved these changes
Thanks @ovista-dept !

2021-07-23 09:22 UTC, merged