WS2-1167 - Article content type updates
ASUWebPlatforms/webspark-theme-renovation pull request #369
Opened 2023-01-31 04:44 UTC by bjdevil21

* Adds article content type TWIG files
* SASS additions for article content type nodes' styling (added recompiled CSS + JS files)

2023-02-01 22:57 UTC, mlsamuelson requested changes
@bjdevil21 Theme needs to be recompiled and updated to break merge conflict.  NOTE: this is why we usually don't do the theme compilation until right before we do a release. Every PR that merges ahead of this that has updated compiled code is going to need to be re-rolled. :P

2023-02-09 20:56 UTC, bjdevil21 commented
Understood. I try to pull in other changes from the main branch but until they're committed to main there's no way of knowing what should be merged.

I've pulled in the other changes from other commits and this should be fine to commit to main.

2023-02-09 20:56 UTC, bjdevil21 commented
@mlsamuelson ^

2023-02-09 21:31 UTC, mlsamuelson approved these changes

2023-02-09 21:31 UTC, merged