WS2-1574: Fix issue related to quotes.
ASUWebPlatforms/webspark-theme-renovation pull request #378
Opened 2023-04-14 20:31 UTC by juanmitriatti

Ticket: https://asudev.jira.com/browse/WS2-1574

This solution includes cases where the user has entered a line break by replacing the occurrence of the '</p><p>' tags with <br>

QA Steps:
- Create a blockquote with a single line of text. The opening and closing quotes should appear on the same line as the text.
- Create a blockquote with line breaks.
- Create a blockquote that contains anchors and line breaks.

2023-04-22 01:53 UTC, bjdevil21 requested changes
One super small thing: change the break tag to match HTML 5 or XHTML standards: 

`</hr> => <hr> OR <hr/>` 

I wondered about the "raw" Twig filter, but the Body field is already being sanitized when the node is saved by the available WYSIWYG filters in the available input formats, IIRC.

2023-04-24 23:25 UTC, bebaps commented
@bjdevil21  `<br>` is HTML5 compliant, and I don't see in the generated markup where it is rendered as self-closing, so I think it's good as is.

@juanmitriatti this is a good fix, but please also consider changing this WYSIWYG field to be plain text. All of the tests you outline do produce the intended results, but leaving it as a WYSIWYG field keeps it open to users just doing things they should not, so the risk of `<p></p>` being inserted still remains.

<img width="1205" alt="Screenshot 2023-04-24 at 4 19 40 PM" src="https://user-images.githubusercontent.com/5995907/234136563-b9f06f95-5b59-4ec2-8eef-e706bb83b17d.png">

2023-04-26 15:28 UTC, juanmitriatti commented
Hello @bebaps  
Thanks for your feedback. You're right. However, if I change the field format from WYSIWYG to plain text, when the user edits the **old** Blockquote components on the site, they will see the html tags. Please check the attached image : 

![bquote](https://user-images.githubusercontent.com/33984278/234624588-c6548323-4bcf-4fe2-9862-01cd89f67272.jpeg)


Anyways, it will work properly for **new** Blockquotes components. A possible solution would be a hook update that removes all the HTML tags. 
CC @mlsamuelson , @bjdevil21

2023-04-28 18:37 UTC, mlsamuelson requested changes
I tested the block before and after this change, and while the intended issue is resolved, there's a security concern introduced.

Before, adding a `<script>alert('gotcha');</script>` script in the source view and saving would result in the tag being sanitized and not displaying. But with the change in this PR, the script executes. We need to ensure that the basic html rules are honored here as they are in other places where we use 'basic html' so scripts can't be inserted and executed.

2023-04-28 22:57 UTC, juanmitriatti commented
Hi @mlsamuelson 
I just updated this PR with a fix that removes all the html tags except anchors and breaks. It means that script element will be remove as well.

Please check my new commit.
Thanks

2023-04-28 23:50 UTC, mlsamuelson approved these changes
@juanmitriatti Issue resolved.

And hey, this now basically does what we wanted! Nice!

2023-04-28 23:52 UTC, merged